## No 1

In [2]:
import numpy as np

In [3]:
import pandas as dp

In [4]:
A = np.array ([[2,2,3],[-2,7,4],[-3,-3,-4],[-8,2,3]])
print(A)

[[ 2  2  3]
 [-2  7  4]
 [-3 -3 -4]
 [-8  2  3]]


# 1. 1

## adding another column to the matrix

In [5]:
# vstack adds a new row
# hstack adds a new column

In [10]:
new_column=np.array([[1],[0],[1],[0]])
new_column

array([[1],
       [0],
       [1],
       [0]])

In [9]:
B=np.hstack((A,new_column))
print(B)

[[ 2  2  3  1]
 [-2  7  4  0]
 [-3 -3 -4  1]
 [-8  2  3  0]]


In [ ]:
## checking if the matrix is invertable we look out for its determinant which is[ np.linalg.det(B)]
#linalg which is "linear aligebra"
determinant= np.linalg.det(B)

In [39]:
if determinant !=0:
           print("matrix B is invertable")
else:
           print ("matrix is not invertable")
#out of matrix
print(B)
print ("daterminant of B",determinant)

matrix B is invertable
[[ 2  2  3  1]
 [-2  7  4  0]
 [-3 -3 -4  1]
 [-8  2  3  0]]
daterminant of B -298.9999999999999


## 1.2

In [40]:
# removing a column from A to make it invertable
A = np.array ([[2,2,3],[-2,7,4],[-3,-3,-4],[-8,2,3]])
print(A)


[[ 2  2  3]
 [-2  7  4]
 [-3 -3 -4]
 [-8  2  3]]


In [41]:
reduced_matrix=np.delete(A,2, axis=0)
print(reduced_matrix)

[[ 2  2  3]
 [-2  7  4]
 [-8  2  3]]


In [42]:
determinant=np.linalg.det(reduced_matrix)
print (determinant)

129.99999999999997


## 1.3

## AA^T (getting the transpos of A)

In [44]:
A = np.array ([[2,2,3],[-2,7,4],[-3,-3,-4],[-8,2,3]])
print(A)

[[ 2  2  3]
 [-2  7  4]
 [-3 -3 -4]
 [-8  2  3]]


# 1.4

## transpose matrix( what is a row becomes a column)


In [51]:
AT=np.array([[2,-2,-3,8],[2,7,-3,2],[3,4,-4,3]])
print(AT)

[[ 2 -2 -3  8]
 [ 2  7 -3  2]
 [ 3  4 -4  3]]


In [52]:
A_AT=np.dot(A,A.T)
print(A_AT)

[[ 17  22 -24  -3]
 [ 22  69 -31  42]
 [-24 -31  34   6]
 [ -3  42   6  77]]


In [50]:
dterminant=np.linalg.det(A_AT)
print(determinant)

129.99999999999997


In [53]:
## ATA invertable

In [55]:
AT_A=np.dot(A.T,A)
print(AT_A)

[[ 81 -17 -14]
 [-17  66  52]
 [-14  52  50]]


In [56]:
determinant-np.linalg.det(AT_A)
print(determinant)

129.99999999999997


In [59]:
if determinant !=0:
    print('invertable')
else:
    print('not invertable')

invertable


## NO 2

## Given an n-darray X = np.array([[25, 2], [5, 26], [3, 7]])

In [60]:
X = np.array ([[25, 2], [5, 26], [3, 7]])
print(X)

[[25  2]
 [ 5 26]
 [ 3  7]]


## 2.1

In [62]:
X.shape

(3, 2)

## 2.2

In [114]:
transpose_X=X.T
print(transpose_X)

[25  2  5]


## Generate a new n-darray of X scaled up by integer 3 (Hint: note that scalars are applied on each element of a matrix)


## 2.3

In [115]:
X = np.array ([[25, 2], [5, 26], [3, 7]])
print(X)

[[25  2]
 [ 5 26]
 [ 3  7]]


In [75]:
scale_X = X*3
print(scale_X)

[[75  6]
 [15 78]
 [ 9 21]]


## Generate a new matrix A = ([[3, 4], [5, 6], [7, 8]]). Compute the matrix multiplication of matrices X and A (note the condition for matrix multiplication must satisfy a certain rule)


## 2.4

In [116]:
A =np.array ([[3, 4], [5, 6], [7, 8]])
print(A)

[[3 4]
 [5 6]
 [7 8]]


In [78]:
X = np.array ([[25, 2], [5, 26], [3, 7]])
print(X)

[[25  2]
 [ 5 26]
 [ 3  7]]


In [80]:
X_and_A=(A*X)
print(X_and_A)

[[ 75   8]
 [ 25 156]
 [ 21  56]]


## Compute the inverse of the result of multiplication of matrices (A and X)

## 2.5

In [117]:
A = np.array([[3,4],[5,6],[7,8]])
print(A)

[[3 4]
 [5 6]
 [7 8]]


In [89]:
transpose = A.T
print(transpose)

[[3 5 7]
 [4 6 8]]


In [92]:
product=np.dot(A.T,X)
print(product)

[[121 185]
 [154 220]]


In [93]:
## inverse of the product is computed as (1/determinant)
determinant=np.linalg.det(product)
print(determinant)

-1869.999999999996


In [95]:
the_inverse=(1/determinant)
print(the_inverse)

-0.0005347593582887713


## No3

# 3.1

In [98]:
X = np.array([25, 2, 5])
print (X)


[25  2  5]


# 3.2

In [101]:
X.shape

(3,)

# 3.3

In [102]:
XT = (X.T)
print(XT)

[25  2  5]


# 3.4

In [112]:
norm_of_x = np.linalg.norm([25, 2, 5])

print("L² (Frobenius) norm of x:", norm_of_x)


L² (Frobenius) norm of x: 25.573423705088842
